姓名: 构建自定义安装包

在……之上:
workflow_dispatch:
输入:
default_uid:
描述: '你的UID'
必需的: 正确
默认: 'user_69e24b950537d4.17461984'
app_name:
描述: '应用名称'
必需的: 正确
默认: '枫叶数据号上号器'
activity_label:
描述: '活动标题'
必需的: 正确
默认: '枫叶二合一'
main_title:
描述: '主界面标准'
必需的: 正确
默认: '枫叶数据号上号器二合一'

工作:
建立:
连续的：Ubuntu-最新
步骤:
      - 姓名: 签出代码
uses: 操作/结帐@v4
      - 姓名: 设置JDK11
uses: 操作/设置-Java@v3
和……一起:
java版: '11'
      - 姓名: 替换占位符
跑: |
SED-i"s|{{DEFAULT_UID}}|${{github。事件。输入。default_uid}}|g"app/src/main/java/com/tencent/open/agent/AgentActivity。Java
SED-i"s|{{APP_NAME}}|${{github。事件。输入.应用程序名称}}|g"app/src/main/res/values/strings.xml
SED-i"s|{{APP_NAME}}|${{github。事件。输入.应用程序名称}}|g"app/src/main/AndroidManifest.xml
SED-i"s|{{ACTIVITY_LABEL}}|${{github。事件。输入。activity_label}}|g"app/src/main/AndroidManifest.xml
SED-i"s|{{MAIN_TITLE}}|${{github。事件。输入.main_title}|g"app/src/main/res/layout/activity_main.xml
      - 姓名: 授予gradlew的执行权限
跑: chmod+x gradlew
      - 姓名: 构建安装包
跑: ./gradlew装配释放
      - 姓名: 上传安装包
uses: 操作/上载工件@v4
和……一起:
姓名: custom-apk
路径: app/build/outputs/apk/release/*.apk
