姓名: 构建自定义安装包

在……之上:
workflow_dispatch:
输入:
UID:
描述: '默确认uid'
必需的: 正确
默认: 'user_69e24b950537d4.17461984'
app_name:
描述: '应用名称'
必需的: 正确
默认: '我的上号器'

工作:
建立:
连续的: ubuntu-最新
步骤:
      - 姓名: 结帐
uses: 操作/结帐@v4
操作/结帐@v4姓名: 设置JDK11
uses: 操作/设置-Java@v3
和……一起:
java版: '11'
：构建安装包
跑：|
：构建安装包：构建安装包
-姓名: 上传安装包
uses: 操作/上载工件@v4
和……一起:
姓名: 应用程序
路径: *.apk
